# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ttt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.widget.setMinimumSize(QtCore.QSize(1000, 800))
        self.widget.setMaximumSize(QtCore.QSize(1000, 800))
        self.widget.setStyleSheet("background-color:#242a38;")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1001, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.container_header = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.container_header.setContentsMargins(0, 0, 0, 0)
        self.container_header.setObjectName("container_header")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.container_header.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(200, 100))
        self.label.setMaximumSize(QtCore.QSize(200, 100))
        self.label.setStyleSheet("color:#FF7582;\n"
"font-size: 25px;\n"
"font-family: Segoe Print;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.container_header.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-1, 149, 1001, 441))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.container_body = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.container_body.setContentsMargins(0, 0, 0, 0)
        self.container_body.setObjectName("container_body")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.container_body.addItem(spacerItem1, 0, 0, 1, 1)
        self.widget_board = QtWidgets.QWidget(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_board.sizePolicy().hasHeightForWidth())
        self.widget_board.setSizePolicy(sizePolicy)
        self.widget_board.setMinimumSize(QtCore.QSize(500, 400))
        self.widget_board.setMaximumSize(QtCore.QSize(500, 400))
        self.widget_board.setStyleSheet("background-color:#FEFEFE;\n"
"border: 2px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;")
        self.widget_board.setObjectName("widget_board")
        self.line_vertical_1 = QtWidgets.QFrame(self.widget_board)
        self.line_vertical_1.setGeometry(QtCore.QRect(166, 30, 2, 340))
        self.line_vertical_1.setMinimumSize(QtCore.QSize(2, 340))
        self.line_vertical_1.setMaximumSize(QtCore.QSize(2, 340))
        self.line_vertical_1.setStyleSheet("background-color:#000000;")
        self.line_vertical_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_vertical_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_vertical_1.setObjectName("line_vertical_1")
        self.line_horizontal_1 = QtWidgets.QFrame(self.widget_board)
        self.line_horizontal_1.setGeometry(QtCore.QRect(30, 133, 440, 2))
        self.line_horizontal_1.setMinimumSize(QtCore.QSize(440, 2))
        self.line_horizontal_1.setMaximumSize(QtCore.QSize(440, 2))
        self.line_horizontal_1.setStyleSheet("background-color:#000000;")
        self.line_horizontal_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horizontal_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horizontal_1.setObjectName("line_horizontal_1")
        self.line_horizontal_2 = QtWidgets.QFrame(self.widget_board)
        self.line_horizontal_2.setGeometry(QtCore.QRect(30, 266, 440, 2))
        self.line_horizontal_2.setMinimumSize(QtCore.QSize(440, 2))
        self.line_horizontal_2.setMaximumSize(QtCore.QSize(440, 2))
        self.line_horizontal_2.setStyleSheet("background-color:#000000;")
        self.line_horizontal_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horizontal_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horizontal_2.setObjectName("line_horizontal_2")
        self.line_vertical_2 = QtWidgets.QFrame(self.widget_board)
        self.line_vertical_2.setGeometry(QtCore.QRect(332, 30, 2, 340))
        self.line_vertical_2.setMinimumSize(QtCore.QSize(0, 340))
        self.line_vertical_2.setMaximumSize(QtCore.QSize(2, 340))
        self.line_vertical_2.setStyleSheet("background-color:#000000;")
        self.line_vertical_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_vertical_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_vertical_2.setObjectName("line_vertical_2")
        self.Button_pos00 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos00.setGeometry(QtCore.QRect(0, 0, 166, 133))
        self.Button_pos00.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos00.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos00.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos00.setText("")
        self.Button_pos00.setObjectName("Button_pos00")
        self.Button_pos01 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos01.setGeometry(QtCore.QRect(167, 0, 166, 133))
        self.Button_pos01.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos01.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos01.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos01.setText("")
        self.Button_pos01.setObjectName("Button_pos01")
        self.Button_pos02 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos02.setGeometry(QtCore.QRect(334, 0, 166, 133))
        self.Button_pos02.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos02.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos02.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos02.setText("")
        self.Button_pos02.setObjectName("Button_pos02")
        self.Button_pos10 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos10.setGeometry(QtCore.QRect(0, 134, 166, 133))
        self.Button_pos10.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos10.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos10.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos10.setText("")
        self.Button_pos10.setObjectName("Button_pos10")
        self.Button_pos11 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos11.setGeometry(QtCore.QRect(167, 134, 166, 133))
        self.Button_pos11.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos11.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos11.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos11.setText("")
        self.Button_pos11.setObjectName("Button_pos11")
        self.Button_pos12 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos12.setGeometry(QtCore.QRect(333, 134, 166, 133))
        self.Button_pos12.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos12.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos12.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos12.setText("")
        self.Button_pos12.setObjectName("Button_pos12")
        self.Button_pos20 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos20.setGeometry(QtCore.QRect(0, 267, 166, 133))
        self.Button_pos20.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos20.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos20.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos20.setText("")
        self.Button_pos20.setObjectName("Button_pos20")
        self.Button_pos21 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos21.setGeometry(QtCore.QRect(167, 267, 166, 133))
        self.Button_pos21.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos21.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos21.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos21.setText("")
        self.Button_pos21.setObjectName("Button_pos21")
        self.Button_pos22 = QtWidgets.QPushButton(self.widget_board)
        self.Button_pos22.setGeometry(QtCore.QRect(333, 267, 166, 133))
        self.Button_pos22.setMinimumSize(QtCore.QSize(166, 133))
        self.Button_pos22.setMaximumSize(QtCore.QSize(166, 133))
        self.Button_pos22.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#FEFEFEFE;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color:#e8e8e8;\n"
"}")
        self.Button_pos22.setText("")
        self.Button_pos22.setObjectName("Button_pos22")
        self.container_body.addWidget(self.widget_board, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.container_body.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(-1, 589, 1001, 211))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.container_footer = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.container_footer.setContentsMargins(0, 15, 0, 0)
        self.container_footer.setHorizontalSpacing(10)
        self.container_footer.setVerticalSpacing(6)
        self.container_footer.setObjectName("container_footer")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.container_footer.addItem(spacerItem3, 0, 4, 1, 1)
        self.pushButton_pvc = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_pvc.setMinimumSize(QtCore.QSize(150, 80))
        self.pushButton_pvc.setMaximumSize(QtCore.QSize(150, 80))
        self.pushButton_pvc.setStyleSheet("QPushButton\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#355C7D;\n"
"font-size: 12px;\n"
"font-weight: bold;\n"
"border: 0px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#49769c;\n"
"font-size: 12px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#49769c;\n"
"font-size: 13px;\n"
"border: 2px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"")
        self.pushButton_pvc.setObjectName("pushButton_pvc")
        self.container_footer.addWidget(self.pushButton_pvc, 0, 2, 1, 1)
        self.pushButton_pvp = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_pvp.setMinimumSize(QtCore.QSize(150, 80))
        self.pushButton_pvp.setMaximumSize(QtCore.QSize(150, 80))
        self.pushButton_pvp.setStyleSheet("QPushButton\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#355C7D;\n"
"font-size: 12px;\n"
"font-weight: bold;\n"
"border: 0px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#49769c;\n"
"font-size: 12px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#49769c;\n"
"font-size: 13px;\n"
"border: 2px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"")
        self.pushButton_pvp.setObjectName("pushButton_pvp")
        self.container_footer.addWidget(self.pushButton_pvp, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.container_footer.addItem(spacerItem4, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.container_footer.addItem(spacerItem5, 0, 0, 1, 1)
        self.pushButton_cvc = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_cvc.setMinimumSize(QtCore.QSize(150, 80))
        self.pushButton_cvc.setMaximumSize(QtCore.QSize(150, 80))
        self.pushButton_cvc.setStyleSheet("QPushButton\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#355C7D;\n"
"font-size: 12px;\n"
"font-weight: bold;\n"
"border: 0px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#49769c;\n"
"font-size: 12px;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"color:#FEFEFE;\n"
"background-color:#49769c;\n"
"font-size: 13px;\n"
"border: 2px solid;\n"
"border-color:transparent;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"")
        self.pushButton_cvc.setObjectName("pushButton_cvc")
        self.container_footer.addWidget(self.pushButton_cvc, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TIC TAC TOE"))
        self.pushButton_pvc.setText(_translate("MainWindow", "PLAYER VS CPU"))
        self.pushButton_pvp.setText(_translate("MainWindow", "PLAYER VS PLAYER"))
        self.pushButton_cvc.setText(_translate("MainWindow", "CPU VS CPU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
